### ISSUE TITLE
Integer overflow in parser

### ISSUE THREAD

**Issue by dtolnay** [pikkr/pikkr#13]
Discovered by https://github.com/rust-fuzz/targets/pull/89:

```rust
extern crate pikkr;

fn main() {
    let j = b"\\\":";
    let q = vec!["$.a".as_bytes()];
    pikkr::Pikkr::new(&q, 1).parse(j);
}
```

```
thread 'main' panicked at 'attempt to subtract with overflow', .cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.5.1/src/parser.rs:26:15
stack backtrace:
  10: pikkr::parser::basic_parse
             at .cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.5.1/src/parser.rs:26
  11: pikkr::pikkr::Pikkr::parse
             at .cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.5.1/src/pikkr.rs:110
  12: testing::main
             at src/main.rs:6
```

**Comment by kjmrknsn** [comment]
Closed by #41
